# Site settings
author: Megan 'Pilahi" Moran
title: Flower at Flatiron
header-img: img/home-bg.png
email: kamokumoran@gmail.com
copyright_name: Megan 'Pilahi" Moran
description: > # this means to ignore newlines until "baseurl:"
  Flower Obsessed and Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mpmoran2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
